# Import Library

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import Dataset

In [2]:
dataset = pd.read_csv('/content/Data Kota Noise.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)
print(y)

[['Semarang' 22.0 3000000.0]
 ['Bekasi' 23.0 4000000.0]
 ['Kalimantan Utara' 22.0 4500000.0]
 ['Kalimantan Timur' 24.0 nan]
 ['Purbalingga' 25.0 2500000.0]
 ['Purwokerto' 30.0 2750000.0]
 ['Jakarta' nan 5000000.0]
 ['Surbaya' 20.0 4200000.0]
 ['Bandung' 33.0 3000000.0]
 ['Solo' 32.0 2700000.0]]
['No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes']


# Menghilangkan Missing Value (NaN)

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [5]:
print(x)

[['Semarang' 22.0 3000000.0]
 ['Bekasi' 23.0 4000000.0]
 ['Kalimantan Utara' 22.0 4500000.0]
 ['Kalimantan Timur' 24.0 3516666.6666666665]
 ['Purbalingga' 25.0 2500000.0]
 ['Purwokerto' 30.0 2750000.0]
 ['Jakarta' 25.666666666666668 5000000.0]
 ['Surbaya' 20.0 4200000.0]
 ['Bandung' 33.0 3000000.0]
 ['Solo' 32.0 2700000.0]]


# Encoding Data Category (Atribut)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

  (0, 7)	1.0
  (0, 10)	22.0
  (0, 11)	3000000.0
  (1, 1)	1.0
  (1, 10)	23.0
  (1, 11)	4000000.0
  (2, 4)	1.0
  (2, 10)	22.0
  (2, 11)	4500000.0
  (3, 3)	1.0
  (3, 10)	24.0
  (3, 11)	3516666.6666666665
  (4, 5)	1.0
  (4, 10)	25.0
  (4, 11)	2500000.0
  (5, 6)	1.0
  (5, 10)	30.0
  (5, 11)	2750000.0
  (6, 2)	1.0
  (6, 10)	25.666666666666668
  (6, 11)	5000000.0
  (7, 9)	1.0
  (7, 10)	20.0
  (7, 11)	4200000.0
  (8, 0)	1.0
  (8, 10)	33.0
  (8, 11)	3000000.0
  (9, 8)	1.0
  (9, 10)	32.0
  (9, 11)	2700000.0


# Encoding Data Category (Class/Label)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
print(y)

[0 0 1 0 1 0 1 0 1 1]


# Membagi Dataset ke Training set & Test set

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

x = x[0, 0]
x = x.toarray().reshape(10, -1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.56666667e+01 5.00000000e+06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.50000000e+01 2.50000000e+06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 2.20000000e+01 3.00000000e+06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.40000000e+01 3.51666667e+06]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.30000000e+01 4.00000000e+06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0

In [16]:
print(x_test)

[[0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00
  0.0e+00 2.2e+01 4.5e+06]
 [0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00
  0.0e+00 3.2e+01 2.7e+06]]


In [17]:
print(y_train)

[1 1 0 0 0 0 1 0]


In [18]:
print(y_test)

[1 1]


# Feature Scaling

In [19]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [20]:
print(x_train)

[[ 0.          0.          1.         -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  0.         -0.37796447  0.08347839  1.89270018]
 [ 0.          0.          0.         -0.37796447  0.          2.64575131
  -0.37796447 -0.37796447  0.         -0.37796447 -0.08347839 -1.25306189]
 [ 0.          0.          0.         -0.37796447  0.         -0.37796447
  -0.37796447  2.64575131  0.         -0.37796447 -0.83478387 -0.62390948]
 [ 0.          0.          0.          2.64575131  0.         -0.37796447
  -0.37796447 -0.37796447  0.         -0.37796447 -0.33391355  0.02621468]
 [ 0.          1.          0.         -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  0.         -0.37796447 -0.58434871  0.63439535]
 [ 0.          0.          0.         -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  0.          2.64575131 -1.33565419  0.88605632]
 [ 1.          0.          0.         -0.37796447  0.         -0.37796447
  -0.37796447 -0.37796447  0.   

In [21]:
print(y_train)

[1 1 0 0 0 0 1 0]
